---
server:
  port: 8080
  servlet:
    contextPath: /api/v1

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
  httpclient:
    disableSslValidation: true

client:
  visa:
    baseUrl: "https://sandbox.api.visa.com"
    apiKey: "ETTDNFOWT57R8FNGOWBH21LD3QZlBgvRdehaNLjR1HYW5cwH4"
    sharedSecret: "XO8bbmBed4/Qy-Ayw$W1m40mF9{bC-WiaHB}G0/M"
    resourcePath: "helloworld"
    helloWorldApi: "/vdp/helloworld?apikey=ETTDNFOWT57R8FNGOWBH21LD3QZlBgvRdehaNLjR1HYW5cwH4"

